name: RandomThings
version: '${project.version}'
main: com.mrnatsu.RandomThings
api-version: 1.17
commands:
  fly:
    usage: /<command>
    description: a flying command
    permission: random.fly
  skin:
    usage: /<command>
    description: a skin command
    permission: random.skin
  ping:
    usage: /<command>
    description: a ping command
    permission: random.ping

permissions:
  random.fly:
    default: op
  random.ping:
    default: op
  random.skin:
    default: op